# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/24ddf333-cfc6-4ae6-bf00-94a3043cb2d3";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=lzo" "space_cache=v2" "discard=async" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/24ddf333-cfc6-4ae6-bf00-94a3043cb2d3";
      fsType = "btrfs";
      options = [ "subvol=nix"  "compress=lzo" "space_cache=v2" "discard=async" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/24ddf333-cfc6-4ae6-bf00-94a3043cb2d3";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=lzo" "space_cache=v2" "discard=async" "noatime" ];
    };

  fileSystems."/var/lib" =
    { device = "/dev/disk/by-uuid/24ddf333-cfc6-4ae6-bf00-94a3043cb2d3";
      fsType = "btrfs";
      options = [ "subvol=lib" "compress=lzo" "space_cache=v2" "discard=async" "noatime" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/24ddf333-cfc6-4ae6-bf00-94a3043cb2d3";
      fsType = "btrfs";
      options = [ "subvol=log" "compress=lzo" "space_cache=v2" "discard=async" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/887B-A4FE";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/02e3406d-5ccd-4fdd-8451-d004853b628a"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
